#!/usr/bin/env python3
"""Write the changelog source, scripts/docs/eng/changelog.md, from closed GitHub issues and the commits of this repository.

Grouped by day, newest first, and within each day by Added, Changed and Fixed:
- a closed issue with a type label: 'type: feature' -> Added, 'type: bug' -> Fixed, 'type: docs' or 'type: chore' -> Changed;
  issues without a type label are left out (the same triage rule as the board);
- a commit by a person or an agent session, minus the conformity bot's commits and commits that touch only the map
  snapshot or the conformity record: Fixed when the subject says fix, repair, correct or restore; Added when it says add
  or new, or names a new page path (' at /'); Changed otherwise.

A subject that would trip the gate's placeholder check, or that carries an address, is set as code or left out.
Needs the network for the issues (gh if installed, else the anonymous API). Run before scripts/build_docs.py:
    python3 scripts/build_changelog.py && python3 scripts/build_docs.py
"""
import datetime, json, re, shutil, subprocess, sys, urllib.request
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'scripts' / 'docs' / 'eng' / 'changelog.md'
REPO = 'uncovertechtalent/machinebehavior.io'
URL = f'https://github.com/{REPO}'
TODAY = datetime.date.today()
SKIP_ONLY = {'map/graph.json', 'conformity/latest.json', 'conformity/index.html'}
PLACEHOLDER = re.compile(json.loads((ROOT / 'conformity' / 'site-tier.json').read_text())['placeholder_pattern'])
PRIVATE = re.compile(r'\b\d{1,3}(?:\.\d{1,3}){3}\b|(?<![\w/])\.\d{1,3}\b|@|\.local\b|\.lan\b', re.I)
FIX = re.compile(r'\b(fix|fixes|fixed|repair|repaired|correct|corrected|restore|restored|back as|broken)\b', re.I)
ADD = re.compile(r'\b(add|adds|added|new|introduce|introduces|launch|first)\b|\sat /', re.I)


def issues():
    q = f'repos/{REPO}/issues?state=closed&per_page=100'
    if shutil.which('gh'):
        out = subprocess.run(['gh', 'api', q, '--paginate'], capture_output=True, text=True)
        if out.returncode == 0:
            return json.loads(out.stdout.replace('][', ','))
    req = urllib.request.Request('https://api.github.com/' + q, headers={'Accept': 'application/vnd.github+json', 'User-Agent': 'changelog build'})
    return json.load(urllib.request.urlopen(req, timeout=20))


def commits():
    fmt = '%x1e%H%x1f%cs%x1f%an%x1f%s'
    log = subprocess.run(['git', 'log', '--no-merges', f'--format={fmt}', '--name-only'], cwd=ROOT, capture_output=True, text=True).stdout
    for rec in log.split('\x1e')[1:]:
        head, _, files = rec.partition('\n')
        sha, day, author, subject = head.split('\x1f')
        files = {f for f in files.split('\n') if f.strip()}
        if author == 'conformity-bot' or '[skip ci]' in subject or (files and files <= SKIP_ONLY):
            continue
        yield sha, day, subject


def text(s):
    s = s.replace('|', '/').strip()
    if PLACEHOLDER.search(s):
        return '`' + s.replace('`', "'") + '`'
    return s


def main():
    days = defaultdict(lambda: {'Added': [], 'Changed': [], 'Fixed': []})
    n_issues = n_commits = skipped = 0
    for i in issues():
        if i.get('pull_request') or not i.get('closed_at'):
            continue
        labels = {l['name'] for l in i['labels']}
        kind = 'Added' if 'type: feature' in labels else 'Fixed' if 'type: bug' in labels else \
            'Changed' if labels & {'type: docs', 'type: chore'} else None
        if not kind or PRIVATE.search(i['title']):
            continue
        days[i['closed_at'][:10]][kind].append(f'{text(i["title"])} ([#{i["number"]}]({URL}/issues/{i["number"]}))')
        n_issues += 1
    for sha, day, subject in commits():
        if PRIVATE.search(subject):
            skipped += 1
            continue
        kind = 'Fixed' if FIX.search(subject) else 'Added' if ADD.search(subject) else 'Changed'
        days[day][kind].append(f'{text(subject)} ([{sha[:7]}]({URL}/commit/{sha}))')
        n_commits += 1
    first = min(days)
    body = (f'What changed on machinebehavior.io and the platform behind it, newest first: {n_issues} closed issues and {n_commits} commits '
            f'since {first}, grouped by day into Added, Changed and Fixed. Generated by `scripts/build_changelog.py` from the '
            f'[closed issues]({URL}/issues?q=is%3Aissue+is%3Aclosed) and the [commit history]({URL}/commits/main); the conformity bot\'s '
            'commits and map snapshot refreshes are left out. Decisions behind the changes: [Decision records](doc:eng/decision-log).\n')
    body += '\n> [!info] How an entry is sorted. A closed issue goes by its type label: feature to Added, bug to Fixed, docs or chore to Changed. A commit goes to Fixed when its subject says fix, repair, correct or restore, to Added when it says add or new or names a new page path, and to Changed otherwise. The rule reads words, so a few commits land in the wrong group.\n'
    for day in sorted(days, reverse=True):
        body += f'\n## {day}\n'
        for kind in ('Added', 'Changed', 'Fixed'):
            if days[day][kind]:
                body += f'\n### {kind}\n\n' + ''.join(f'- {e}\n' for e in days[day][kind])
    fm = ['title: Changelog', 'summary: What changed on machinebehavior.io and the platform behind it, by day and grouped Added, Changed and Fixed, generated from closed issues and commits.',
          'order: 85', 'labels: changelog, releases, history', f'created: {first}', f'updated: {TODAY.isoformat()}', 'owner: Stefan Coetzee',
          f'reviewed: {TODAY.isoformat()}', f'review_by: {(TODAY + datetime.timedelta(days=90)).isoformat()}', 'type: reference']
    OUT.write_text('\n'.join(fm) + '\n---\n' + body, encoding='utf-8')
    print(f'changelog: {n_issues} issues, {n_commits} commits, {len(days)} days' + (f'; {skipped} commits left out (address in subject)' if skipped else ''))


if __name__ == '__main__':
    sys.exit(main())
